#!/usr/bin/sh

IPA_DIR="/usr/share/ipa"  #TODO find appropriate dir
DAEMON_DIR="ipadnssecd"

FILES=*.py

mkdir -p "$IPA_DIR/$DAEMON_DIR"
mkdir -p /etc/ipa/dnssec
cat > /etc/ipa/dnssec/softhsm2.conf << EOF
# SoftHSM v2 configuration file
# File generated by IPA instalation
directories.tokendir = /var/lib/ipa/dnssec/tokens
objectstore.backend = file
EOF

for file in $FILES
do
	ln --force -s "$(pwd)/$file" "$IPA_DIR/$DAEMON_DIR/$file"
done

ln --force -s "$(pwd)/ipa-dnskeysyncd.service" /lib/systemd/system/ipa-dnskeysyncd.service
ln --force -s "$(pwd)/ipa-ods-exporter.service" /lib/systemd/system/ipa-ods-exporter.service 
ln --force -s "$(pwd)/ipa-ods-exporter.socket" /lib/systemd/system/ipa-ods-exporter.socket
ln --force -s "$(pwd)/sysconfig/ipa-dnskeysyncd" /etc/sysconfig/ipa-dnskeysyncd
ln --force -s "$(pwd)/sysconfig/ipa-ods-exporter" /etc/sysconfig/ipa-ods-exporter
systemctl daemon-reload
